### ISSUE TITLE
AirPlay volume cannot be changed on the Sonos speaker

### ISSUE THREAD

**Issue by Andreas221988** [philippe44/LMS-Raop#24]
Hi philippe44,

I have integrated my Sonos via AirPlay now I can no longer change the volume using the buttons on the speaker or

Why is that?

Just tested if I play something from the iPhone via AirPlay, I can control the volume with the LS buttons and Alexa as normal.

Thanks and best regards

**Comment by philippe44** [comment]
It's probably that the remote controller of Sonos is using some AirPlay2 mode (guessing) and I don't support AirPlay2

**Comment by Andreas221988** [comment]
is AirPlay 2 support planned?

**Comment by philippe44** [comment]
No

**Comment by Andreas221988** [comment]
Why?

**Comment by philippe44** [comment]
No benefit and a lot of work

**Comment by Andreas221988** [comment]
All Sonos users would thank you that would be really great if that worked

**Comment by philippe44** [comment]
They can be used in UPnP mode where remote volume works (of course you don't have sync then). I don't have time currently and everything one does for free must be of some benefit for self to create motivation and I don't own new Sonos devices, only PLAY:3 and PLAY:5

**Comment by Andreas221988** [comment]
okay anyway thank you very much

**Comment by Andreas221988** [comment]
my Bose SoundTouch 20 Series 2 interferes with the AirPlay as soon as the speaker is on, no AirPlay speakers are found
