### ISSUE TITLE
Hos to rescan disconnected airplay device?

### ISSUE THREAD

**Issue by fmalfatto** [philippe44/LMS-Raop#26]
I noticed that I switch off an old Sony speaker, LMS loses it until the server is restarted, also if the device is powered on again and reached on the network. Is there a way to rescan devices? I have LMS under piCorePlayer and your plugin works very well.
TY in advance

**Comment by philippe44** [comment]
There is already an automatic rescan every 30s

**Comment by fmalfatto** [comment]
Made some test starting with SONY SA-NS410. It's LAN connected with fixed IP 192.168.1.142. The lms server IP is 192.168.1.25

From log: AddRaopDevice:881 [0x1116b8]: adding renderer (SONY)

1) While using it, i disconnected the LAN Cable, simulating a network problem. It switches to Wifi connection and goes on playing music.
2) When the LAN connection comes back, the speaker stops playing until LMS is restarted, After a while it disappears from available devices
3) After restarting LMS, the Sony devices returns active and listed in available devices.

[raopbridge.zip](https://github.com/philippe44/LMS-to-Raop/files/7149261/raopbridge.zip)

**Comment by philippe44** [comment]
Try the new dev version, it might have fixed that

**Comment by fmalfatto** [comment]
Done, all is ok now. TY !!!
I did not update LMS for long and I forgot ...
