### ISSUE TITLE
Apple TV 4K 2021

### ISSUE THREAD

**Issue by loadamasta** [philippe44/LMS-Raop#30]
Sometimes, playback does not start. The web frontend displays passed time as 0:00. Sometimes, skip to next song or choosing another radio station does start the playback. But very often only one or multiple restart of the plugin does help. System of squeezebox server: mac os. Version of server 8.2.0 - 1627922070. Log file does not show an error when this happens. Another device (Libratone Box) does not have any problems with the plugin, only the Apple TV 4K.

**Comment by philippe44** [comment]
Missing a bit of context here. Is this new? or due to a new version? has it ever worked?

**Comment by loadamasta** [comment]
The device is new and the effect was from the beginning. Actually, played a song via Spotify (Spotty). Skip to next song: no playback. 
[Log.txt](https://github.com/philippe44/LMS-Raop/files/9954785/Log.txt)

**Comment by philippe44** [comment]
This log seems to indicate that the ATV is constantly flip-flopping IP addresses between, x.y.0.200 and x.y.0.96 which confused the player.

**Comment by philippe44** [comment]
There can be two reasons: the address is actually changing and that means you have a conflict or a problem with your DHCP server (router) or the way the ATV is announce is creating a problem with my mDNS service discovery. I'm not sure how the later can happen, unless recent ATV have two different IP addresses. If you are comfortable enough with that, you can find here https://github.com/philippe44/mdnssd/tree/master/bin my standalone service discovery tool. Run it with "-v _raop._tcp.local" as a parameters and capture the result.
