### ISSUE TITLE
Possible to use an airplay device as source?

### ISSUE THREAD

**Issue by kylepyke** [philippe44/LMS-Raop#32]
Is it possible to use an airplay device as an input stream? For example, I'd love to stream from my AppleTV to other LMS devices.

**Comment by philippe44** [comment]
Depends what you mean by input but Shairtunes that I now maintain allows you to turn LMS devices into AirPlay clients, so that anything that knows how to send to an AirPlay can send to an LMS « clone »

**Comment by kylepyke** [comment]
Interesting. I will check this out. Is playback managed in LMS? In otherwords, can you control a device streaming to LMS?

Thanks for all of your work on these plugins!!!!

**Comment by philippe44** [comment]
LMS as a command line interface that allows programmatical control of players

**Comment by philippe44** [comment]
Sorry but this is not fully clear in a sense that you say stream « from » an LMS device not stream « to » an LMS device. Why don’t you describe what you want to achieve in more details?

**Comment by kylepyke** [comment]
Apologies if I wasn't clear. My devices (Wiim Mini player) have an ADC. I'd like to be able to plug an audio source into one of them (e.g. a record player) and have it stream to other LMS devices. The same way you would pull up a remote http stream in LMS, I'd like to pull up a stream from a local device.

The [Wiim mini player](https://wiimhome.com/WiiMMini/guides) specifically, is airplay compatible as a device to both stream from and stream to.

**Comment by philippe44** [comment]
If this is an AirPlay « source » then it has a UI to select what and where to play. Where can be any LMS device when Shairtunes plugin has been installed. 

Another solution that the Wiim might offer is a simple HTTP stream from what is connected to the audio IN. Like a webradio. Then LMS would be able to use that stream to play it anywhere.
