### ISSUE TITLE
v1.2.5 - Compatibility issue with LMS v8.1.1 - 1610364019 - DSM 6 x86_64-linux

### ISSUE THREAD

**Issue by mlebailly** [philippe44/LMS-Raop#33]
The upgrade to the last version 1.2.5 has been proposed by LMS. Since, the plugin won't work anymore on my LMS 8.1.1 setup as it's clearly written in the plugin manager and ask me to upgrade the entire LMS to a newer version. 

I am still running one of the last SPK image of LMS that has been computed with an old PEARL package v 5.2.4, and I don't intend to upgrade to a newer version (Docker upgrade of LMS is needed).

Would it be possible to check why the plugin is not working anymore ?

**Comment by mlebailly** [comment]
Hi,

Did you fix this issue with your last code update of the plug-in ?

**Comment by philippe44** [comment]
Was partly done - I've completed it now
