### ISSUE TITLE
Crash afer entering Pairing Pin for Apple TV

### ISSUE THREAD

**Issue by harrybu** [philippe44/LMS-Raop#41]
When click pair on an Apple TV device, the Airplay Code shows up at the Apple TV. When I enter the Pin and click submit, the AppleTV does not accept it and shows the Code again and again when I submit it again. Then the bridge crashes and restarts.

logfile attached.
[raopbridge.log.zip](https://github.com/philippe44/LMS-Raop/files/14076431/raopbridge.log.zip)

**Comment by philippe44** [comment]
You are probably using a version of Perl and a CPU for which I have not yet built the crypto binaries, so the paring fail when using Perl "integrated" mode. Meanwhile, you can manually start the bridge helper with the -l option and it will get the credentials only using the helper. This means you need to know where your config is, open a terminal and launch it

The helper is here : /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/RaopBridge/Bin/squeeze2raop-linux-aarch64
so I guess your config file is there /var/lib/squeezeboxserver/prefs/raopbridge.xml (you can see the path in plugin's settings).

So you type : 
/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/RaopBridge/Bin/squeeze2raop-linux-aarch64 -l -x  /var/lib/squeezeboxserver/prefs/raopbridge.xml and follow instructions

**Comment by harrybu** [comment]
Worked like a charm!! Thanks very much!! :)
